import { v4 as uuidv4 } from 'uuid';

const now = new Date();
const hours = (h) => new Date(now.getTime() - h * 3600000).toISOString();
const mins = (m) => new Date(now.getTime() - m * 60000).toISOString();

export const mockTickets = [
  {
    id: uuidv4(),
    subject: 'Payment gateway completely down - losing revenue',
    description: 'Our entire payment processing system has been down for the past 2 hours. We are unable to process any transactions and are losing significant revenue. This is affecting all of our customers and needs immediate attention. Error code: PG-5001. Multiple customers have called in angry about failed payments.',
    customer: { name: 'David Mitchell', email: 'david@techcorp.com', company: 'TechCorp Inc.', tier: 'Enterprise' },
    category: 'Technical',
    status: 'escalated',
    urgency: 'critical',
    sentiment: 'angry',
    sentimentScore: 0.92,
    assignedTo: 'a5',
    createdAt: mins(15),
    updatedAt: mins(5),
    slaDeadline: hours(-1),
    aiAnalysis: {
      summary: 'Critical payment gateway outage affecting enterprise customer. Immediate revenue impact detected. Multiple error reports indicate systemic failure at payment processor level.',
      suggestedResponse: 'Dear David, I understand the urgency of this situation and sincerely apologize for the disruption to your payment processing. I\'ve escalated this to our engineering team\'s highest priority queue. Our payment infrastructure team is actively investigating error code PG-5001. We\'ll provide status updates every 15 minutes until resolution. In the meantime, I can provide you with our backup payment endpoint as a temporary workaround.',
      keyEntities: ['Payment Gateway', 'Error PG-5001', 'Revenue Loss'],
      similarTickets: 3,
      estimatedResolution: '1-2 hours',
      confidence: 0.96,
    },
    tags: ['payment', 'outage', 'enterprise', 'critical'],
    messages: [
      { role: 'customer', content: 'Our payment system is completely DOWN. We are losing thousands of dollars every hour!', time: mins(15) },
      { role: 'agent', content: 'I understand the severity. I\'m escalating this immediately to our engineering team.', time: mins(12) },
      { role: 'customer', content: 'This is unacceptable. We need this fixed NOW.', time: mins(8) },
    ],
  },
  {
    id: uuidv4(),
    subject: 'Cannot access dashboard after password reset',
    description: 'I reset my password yesterday and now I cannot log into the dashboard at all. I\'ve tried multiple browsers and clearing cache. Getting a 403 error every time. I have a presentation in 2 hours and need to access my analytics.',
    customer: { name: 'Jessica Williams', email: 'jessica@startupxyz.com', company: 'StartupXYZ', tier: 'Professional' },
    category: 'Account',
    status: 'in_progress',
    urgency: 'high',
    sentiment: 'frustrated',
    sentimentScore: 0.74,
    assignedTo: 'a1',
    createdAt: hours(1),
    updatedAt: mins(30),
    slaDeadline: hours(-0.5),
    aiAnalysis: {
      summary: 'Authentication issue following password reset. Customer facing 403 errors. Time-sensitive due to upcoming presentation. Likely a session token invalidation issue.',
      suggestedResponse: 'Hi Jessica, I\'m sorry you\'re experiencing this issue. Post-password-reset 403 errors typically occur due to cached authentication tokens. I\'ve manually refreshed your session from our end. Could you please: 1) Clear all browser cookies for our domain, 2) Try logging in with an incognito/private window, 3) Use the password you just reset to. If this doesn\'t work, I can generate a temporary access link for your presentation.',
      keyEntities: ['Password Reset', '403 Error', 'Dashboard Access'],
      similarTickets: 8,
      estimatedResolution: '30 minutes',
      confidence: 0.89,
    },
    tags: ['auth', 'access', 'urgent'],
    messages: [
      { role: 'customer', content: 'I reset my password and now I cannot access my dashboard. Getting 403 error.', time: hours(1) },
      { role: 'agent', content: 'I\'m looking into this right now. Can you confirm which browser you\'re using?', time: mins(45) },
    ],
  },
  {
    id: uuidv4(),
    subject: 'API rate limiting affecting our production app',
    description: 'We\'re hitting rate limits on your API that are causing our application to throw errors for end users. We\'ve been a customer for 3 years and our usage hasn\'t changed significantly. Was there a limit change we weren\'t notified about?',
    customer: { name: 'Robert Zhang', email: 'r.zhang@megadev.io', company: 'MegaDev Solutions', tier: 'Enterprise' },
    category: 'Technical',
    status: 'open',
    urgency: 'high',
    sentiment: 'frustrated',
    sentimentScore: 0.68,
    assignedTo: null,
    createdAt: mins(45),
    updatedAt: mins(45),
    slaDeadline: hours(2),
    aiAnalysis: {
      summary: 'Enterprise customer experiencing unexpected API rate limiting. Long-term customer with stable usage patterns - likely indicates a backend configuration change or infrastructure issue on our end.',
      suggestedResponse: 'Hi Robert, thank you for bringing this to our attention. You\'re right - we deployed an infrastructure update that inadvertently modified rate limit thresholds. I\'m coordinating with our platform team to restore your Enterprise-tier limits immediately. As a temporary measure, I can whitelist your API keys for the next 24 hours while we deploy the fix globally.',
      keyEntities: ['API Rate Limiting', 'Production App', 'Enterprise Customer'],
      similarTickets: 5,
      estimatedResolution: '2-4 hours',
      confidence: 0.91,
    },
    tags: ['api', 'rate-limit', 'enterprise', 'production'],
    messages: [
      { role: 'customer', content: 'Our production app is being rate limited unexpectedly. Our users are seeing errors.', time: mins(45) },
    ],
  },
  {
    id: uuidv4(),
    subject: 'Request for team collaboration features',
    description: 'We love the product! Our team has been using it for 6 months and it\'s been great. We\'d love to see real-time collaboration features - similar to how Google Docs works. Multiple team members editing dashboards simultaneously would be amazing.',
    customer: { name: 'Lisa Anderson', email: 'lisa@creativeco.com', company: 'Creative Co', tier: 'Professional' },
    category: 'Feature Request',
    status: 'open',
    urgency: 'low',
    sentiment: 'positive',
    sentimentScore: 0.15,
    assignedTo: null,
    createdAt: hours(3),
    updatedAt: hours(3),
    slaDeadline: hours(20),
    aiAnalysis: {
      summary: 'Feature request for real-time collaboration. Positive sentiment from satisfied long-term customer. Aligns with collaboration features on the product roadmap.',
      suggestedResponse: 'Hi Lisa, thank you for the wonderful feedback - we\'re thrilled to hear your team is getting value from our platform! Real-time collaboration is actually on our Q3 roadmap. I\'ve added your request to the feature voting board and tagged your account for early access when the beta launches. Would you be interested in joining our beta testing group?',
      keyEntities: ['Real-time Collaboration', 'Team Features', 'Dashboard Editing'],
      similarTickets: 12,
      estimatedResolution: 'Product Roadmap',
      confidence: 0.94,
    },
    tags: ['feature', 'collaboration', 'positive'],
    messages: [
      { role: 'customer', content: 'Would love to see real-time collaboration features. Our team would use this daily!', time: hours(3) },
    ],
  },
  {
    id: uuidv4(),
    subject: 'Billing discrepancy - charged twice for March',
    description: 'I\'ve been charged twice for my March subscription. The amounts are $299 on March 1st and $299 on March 15th. I should only be charged once per month. Please refund the duplicate charge immediately. I\'ve attached screenshots of my bank statement.',
    customer: { name: 'Michael Torres', email: 'mike@retailplus.com', company: 'RetailPlus', tier: 'Professional' },
    category: 'Billing',
    status: 'open',
    urgency: 'medium',
    sentiment: 'frustrated',
    sentimentScore: 0.65,
    assignedTo: null,
    createdAt: hours(2),
    updatedAt: hours(2),
    slaDeadline: hours(6),
    aiAnalysis: {
      summary: 'Duplicate billing charge detected. Customer charged $299 twice in March. Billing system likely triggered a double-charge during the mid-month processing cycle update.',
      suggestedResponse: 'Hi Michael, I sincerely apologize for the billing error. I\'ve verified the duplicate charge of $299 on March 15th. I\'ve initiated an immediate refund which should appear in your account within 3-5 business days. I\'ve also added a credit of $15 to your account for the inconvenience. The duplicate was caused by a processing cycle update, and we\'ve fixed the root cause to prevent this from recurring.',
      keyEntities: ['Duplicate Charge', '$299', 'March Billing', 'Refund'],
      similarTickets: 4,
      estimatedResolution: '1 hour',
      confidence: 0.93,
    },
    tags: ['billing', 'refund', 'duplicate-charge'],
    messages: [
      { role: 'customer', content: 'I was charged twice for March. Please refund the duplicate charge of $299.', time: hours(2) },
    ],
  },
  {
    id: uuidv4(),
    subject: 'Data export timing out for large datasets',
    description: 'When I try to export reports with more than 50,000 rows, the export times out after about 3 minutes. This has been happening for the last week. Smaller exports work fine.',
    customer: { name: 'Anna Kowalski', email: 'anna@dataanalytics.io', company: 'DataAnalytics', tier: 'Enterprise' },
    category: 'Bug Report',
    status: 'in_progress',
    urgency: 'medium',
    sentiment: 'neutral',
    sentimentScore: 0.42,
    assignedTo: 'a2',
    createdAt: hours(5),
    updatedAt: hours(1),
    slaDeadline: hours(3),
    aiAnalysis: {
      summary: 'Data export timeout for large datasets (>50K rows). Recent regression - likely related to the export service update deployed last week. Known issue affecting Enterprise-tier users with large datasets.',
      suggestedResponse: 'Hi Anna, thank you for reporting this. We\'ve identified this as a regression from our recent export service update. Our engineering team has already implemented a fix that processes large exports asynchronously. The fix is scheduled for deployment tomorrow. In the meantime, you can work around this by splitting exports into batches of 40,000 rows. I\'ll follow up once the fix is live.',
      keyEntities: ['Data Export', 'Timeout', '50K Rows', 'Regression'],
      similarTickets: 6,
      estimatedResolution: '24 hours',
      confidence: 0.87,
    },
    tags: ['bug', 'export', 'performance', 'regression'],
    messages: [
      { role: 'customer', content: 'Data export times out for reports with more than 50k rows.', time: hours(5) },
      { role: 'agent', content: 'We\'re aware of this issue. Our team is working on a fix.', time: hours(3) },
    ],
  },
  {
    id: uuidv4(),
    subject: 'Security concern - suspicious login attempts',
    description: 'I\'ve received 5 email notifications about failed login attempts to my admin account from IP addresses in countries where we don\'t operate. This is very concerning as we handle sensitive customer data. Please investigate immediately.',
    customer: { name: 'James Wright', email: 'james@securefinance.com', company: 'SecureFinance Ltd', tier: 'Enterprise' },
    category: 'Security',
    status: 'escalated',
    urgency: 'critical',
    sentiment: 'frustrated',
    sentimentScore: 0.78,
    assignedTo: 'a5',
    createdAt: mins(30),
    updatedAt: mins(10),
    slaDeadline: hours(1),
    aiAnalysis: {
      summary: 'Security alert: Multiple unauthorized login attempts on Enterprise admin account. Source IPs from foreign locations. High-risk - finance sector customer with sensitive data. Requires immediate security team investigation.',
      suggestedResponse: 'Hi James, I take this very seriously and have immediately escalated to our security team. Here are the actions we\'ve taken: 1) Temporarily locked your account to prevent unauthorized access, 2) Blocked the suspicious IP addresses at the firewall level, 3) Initiated a security audit of your account activity, 4) Our security team will provide a detailed report within 2 hours. I recommend enabling hardware MFA if you haven\'t already. Would you like me to arrange a call with our security lead?',
      keyEntities: ['Suspicious Login', 'Admin Account', 'Foreign IPs', 'Sensitive Data'],
      similarTickets: 2,
      estimatedResolution: '2-4 hours',
      confidence: 0.95,
    },
    tags: ['security', 'urgent', 'enterprise', 'breach-attempt'],
    messages: [
      { role: 'customer', content: 'Getting suspicious login notifications from foreign IPs. Very concerned about our data.', time: mins(30) },
      { role: 'agent', content: 'Account locked for safety. Security team engaged. Will update shortly.', time: mins(20) },
      { role: 'customer', content: 'Thank you for the quick response. Please send the security report ASAP.', time: mins(10) },
    ],
  },
  {
    id: uuidv4(),
    subject: 'Integration with Salesforce not syncing contacts',
    description: 'Our Salesforce integration stopped syncing contacts about 3 days ago. We haven\'t made any changes on our end. The sync history shows "authentication expired" errors.',
    customer: { name: 'Rachel Green', email: 'rachel@salesteam.co', company: 'SalesTeam Co', tier: 'Professional' },
    category: 'Integration',
    status: 'open',
    urgency: 'medium',
    sentiment: 'neutral',
    sentimentScore: 0.38,
    assignedTo: null,
    createdAt: hours(4),
    updatedAt: hours(4),
    slaDeadline: hours(8),
    aiAnalysis: {
      summary: 'Salesforce integration authentication failure. OAuth tokens likely expired. Common issue after Salesforce API version updates. Simple re-authentication should resolve.',
      suggestedResponse: 'Hi Rachel, the "authentication expired" error typically occurs when Salesforce rotates OAuth tokens. This can happen after Salesforce API updates. To resolve: 1) Go to Settings > Integrations > Salesforce, 2) Click "Reconnect", 3) Re-authorize with your Salesforce admin credentials. This will generate fresh OAuth tokens and resume syncing. All historical data should sync automatically once reconnected. Let me know if you need help!',
      keyEntities: ['Salesforce', 'Contact Sync', 'Auth Expired', 'OAuth'],
      similarTickets: 9,
      estimatedResolution: '15 minutes',
      confidence: 0.92,
    },
    tags: ['integration', 'salesforce', 'sync', 'auth'],
    messages: [
      { role: 'customer', content: 'Salesforce contact sync has been broken for 3 days. Seeing authentication errors.', time: hours(4) },
    ],
  },
  {
    id: uuidv4(),
    subject: 'Mobile app crashes on iOS 18.3',
    description: 'Since updating to iOS 18.3, the app crashes every time I open the reports section. Everything else works fine. iPhone 16 Pro Max.',
    customer: { name: 'Kevin Park', email: 'kevin@mobilefirst.app', company: 'MobileFirst', tier: 'Starter' },
    category: 'Bug Report',
    status: 'open',
    urgency: 'medium',
    sentiment: 'neutral',
    sentimentScore: 0.45,
    assignedTo: null,
    createdAt: hours(6),
    updatedAt: hours(6),
    slaDeadline: hours(12),
    aiAnalysis: {
      summary: 'iOS 18.3 compatibility issue causing crashes in reports section. Device-specific issue with iPhone 16 Pro Max. Known WebKit rendering change in iOS 18.3 likely affecting report charts.',
      suggestedResponse: 'Hi Kevin, thank you for reporting this with your device details. We\'ve identified a compatibility issue with iOS 18.3\'s updated WebKit engine that affects our chart rendering in the reports section. Our mobile team has a fix in version 4.2.1 which should be available in the App Store within 48 hours. In the meantime, you can access reports through our mobile web app at app.ourdomain.com as a workaround.',
      keyEntities: ['iOS 18.3', 'App Crash', 'Reports Section', 'iPhone 16 Pro Max'],
      similarTickets: 7,
      estimatedResolution: '48 hours',
      confidence: 0.85,
    },
    tags: ['mobile', 'ios', 'crash', 'bug'],
    messages: [
      { role: 'customer', content: 'App crashes every time I open Reports after updating to iOS 18.3.', time: hours(6) },
    ],
  },
  {
    id: uuidv4(),
    subject: 'Need help setting up SSO with Okta',
    description: 'We\'re looking to set up SSO with our Okta IdP. Could you provide documentation or walk us through the setup process? We have about 500 users to migrate.',
    customer: { name: 'Sandra Liu', email: 'sandra@enterprisetech.com', company: 'EnterpriseTech', tier: 'Enterprise' },
    category: 'Technical',
    status: 'in_progress',
    urgency: 'low',
    sentiment: 'positive',
    sentimentScore: 0.22,
    assignedTo: 'a3',
    createdAt: hours(8),
    updatedAt: hours(2),
    slaDeadline: hours(16),
    aiAnalysis: {
      summary: 'SSO setup request for Okta integration. Enterprise customer with 500 users. Positive sentiment - proactive setup request. Standard implementation process.',
      suggestedResponse: 'Hi Sandra, I\'d be happy to help you set up SSO with Okta! Here\'s what we\'ll need: 1) Your Okta Admin Console access, 2) Your organization\'s domain for email matching. I\'ll send you our detailed SSO setup guide and schedule a 30-minute call with our integrations specialist to walk you through the process. For a 500-user migration, I recommend a phased rollout starting with your IT team to test before enabling for all users.',
      keyEntities: ['SSO', 'Okta', '500 Users', 'Enterprise Migration'],
      similarTickets: 3,
      estimatedResolution: '1-2 days',
      confidence: 0.90,
    },
    tags: ['sso', 'okta', 'enterprise', 'setup'],
    messages: [
      { role: 'customer', content: 'We need to set up SSO with Okta for our 500 users.', time: hours(8) },
      { role: 'agent', content: 'I\'d be happy to help! Let me send you our setup guide.', time: hours(6) },
      { role: 'customer', content: 'Great, looking forward to it!', time: hours(4) },
    ],
  },
  {
    id: uuidv4(),
    subject: 'Performance issues with real-time analytics dashboard',
    description: 'Our real-time analytics dashboard has become extremely slow - takes 15+ seconds to load. We have about 2M events per day and it used to load in under 3 seconds. This slowdown started about a week ago.',
    customer: { name: 'Tom Bradley', email: 'tom@analyticsplus.com', company: 'AnalyticsPlus', tier: 'Enterprise' },
    category: 'Performance',
    status: 'open',
    urgency: 'high',
    sentiment: 'frustrated',
    sentimentScore: 0.71,
    assignedTo: null,
    createdAt: hours(1.5),
    updatedAt: hours(1.5),
    slaDeadline: hours(3),
    aiAnalysis: {
      summary: 'Severe performance degradation on real-time analytics. Load times increased from <3s to 15s+. Enterprise customer processing 2M events/day. Likely related to recent database indexing changes.',
      suggestedResponse: 'Hi Tom, I apologize for the performance degradation. I\'ve flagged this as a high-priority issue with our performance team. Initial analysis suggests this may be related to a recent change in our real-time data indexing strategy. We\'re running diagnostics on your account\'s query patterns now. I expect to have initial findings within the hour. As a temporary measure, our team can provision dedicated compute resources for your real-time queries.',
      keyEntities: ['Real-time Analytics', 'Performance', '15s Load Time', '2M Events'],
      similarTickets: 3,
      estimatedResolution: '4-8 hours',
      confidence: 0.88,
    },
    tags: ['performance', 'analytics', 'enterprise', 'slow'],
    messages: [
      { role: 'customer', content: 'Dashboard takes 15+ seconds to load. Used to be under 3 seconds. Very frustrating.', time: hours(1.5) },
    ],
  },
  {
    id: uuidv4(),
    subject: 'Thank you for the amazing onboarding experience',
    description: 'Just wanted to say thank you! The onboarding session with Sarah was incredibly helpful. She walked us through everything and our team was up and running in less than a day. The product is exactly what we needed.',
    customer: { name: 'Maria Santos', email: 'maria@growthstartup.io', company: 'GrowthStartup', tier: 'Professional' },
    category: 'General',
    status: 'resolved',
    urgency: 'low',
    sentiment: 'positive',
    sentimentScore: 0.08,
    assignedTo: 'a1',
    createdAt: hours(12),
    updatedAt: hours(10),
    slaDeadline: hours(24),
    aiAnalysis: {
      summary: 'Positive feedback about onboarding experience. No action required. Excellent opportunity for testimonial request and NPS survey.',
      suggestedResponse: 'Hi Maria, thank you so much for taking the time to share this feedback - it really made our day! I\'ll make sure Sarah sees your kind words. We\'re thrilled that the onboarding went smoothly and your team is already up and running. If you\'d be interested, we\'d love to feature your experience as a customer story on our website. Also, feel free to reach out anytime you need help as your usage grows!',
      keyEntities: ['Onboarding', 'Positive Feedback', 'Sarah'],
      similarTickets: 0,
      estimatedResolution: 'Resolved',
      confidence: 0.97,
    },
    tags: ['feedback', 'positive', 'onboarding'],
    messages: [
      { role: 'customer', content: 'The onboarding was amazing! Thank you so much.', time: hours(12) },
      { role: 'agent', content: 'Thank you for the kind words! We\'re so happy to hear that. 😊', time: hours(10) },
    ],
  },
];

export const mockAnalytics = {
  totalTickets: 247,
  openTickets: 42,
  resolvedToday: 31,
  avgResponseTime: '12 min',
  avgResolutionTime: '2.4 hours',
  customerSatisfaction: 94.2,
  escalationRate: 8.5,
  slaCompliance: 96.1,
  ticketsByDay: [
    { day: 'Mon', tickets: 38, resolved: 32 },
    { day: 'Tue', tickets: 42, resolved: 38 },
    { day: 'Wed', tickets: 35, resolved: 30 },
    { day: 'Thu', tickets: 47, resolved: 41 },
    { day: 'Fri', tickets: 39, resolved: 35 },
    { day: 'Sat', tickets: 22, resolved: 20 },
    { day: 'Sun', tickets: 24, resolved: 21 },
  ],
  ticketsByCategory: [
    { name: 'Technical', value: 35, color: '#6366f1' },
    { name: 'Billing', value: 22, color: '#22d3ee' },
    { name: 'Account', value: 18, color: '#a78bfa' },
    { name: 'Bug Report', value: 12, color: '#fb7185' },
    { name: 'Feature Request', value: 8, color: '#34d399' },
    { name: 'Security', value: 5, color: '#fbbf24' },
  ],
  ticketsByUrgency: [
    { name: 'Critical', value: 8, color: '#ef4444' },
    { name: 'High', value: 18, color: '#f97316' },
    { name: 'Medium', value: 35, color: '#eab308' },
    { name: 'Low', value: 39, color: '#22c55e' },
  ],
  sentimentTrend: [
    { time: '9AM', angry: 3, frustrated: 8, neutral: 15, positive: 5 },
    { time: '10AM', angry: 2, frustrated: 6, neutral: 18, positive: 7 },
    { time: '11AM', angry: 4, frustrated: 10, neutral: 12, positive: 4 },
    { time: '12PM', angry: 1, frustrated: 5, neutral: 20, positive: 8 },
    { time: '1PM', angry: 3, frustrated: 7, neutral: 14, positive: 6 },
    { time: '2PM', angry: 2, frustrated: 4, neutral: 16, positive: 9 },
    { time: '3PM', angry: 1, frustrated: 6, neutral: 19, positive: 7 },
    { time: '4PM', angry: 2, frustrated: 5, neutral: 17, positive: 8 },
  ],
  responseTimeTrend: [
    { hour: '9AM', avg: 8 },
    { hour: '10AM', avg: 12 },
    { hour: '11AM', avg: 15 },
    { hour: '12PM', avg: 18 },
    { hour: '1PM', avg: 14 },
    { hour: '2PM', avg: 10 },
    { hour: '3PM', avg: 11 },
    { hour: '4PM', avg: 9 },
  ],
};
